[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.2", features = ["postgres"] }
dotenv = "0.15.0"
tokio = { version = "1.32.0", features = ["full"] }